import { useCallback } from "react";
import { Lock, Route } from "lucide-react";

import type { ShareContribution } from "@/components/share/contribution";
import { iconSvg } from "@/lib/icon-svg";
import type { ReportStat } from "@/lib/report";
import { ORDER, refOf, type PlacedSection } from "@/lib/report-parts";
import { useT, type T } from "@/i18n/useT";
import { ResourceType } from "@/lib/resource-registry";
import type { IngressClassBinding, IngressInfo } from "@/generated/types";

export function ingressStats(
  ingress: IngressInfo,
  controller: IngressClassBinding | undefined,
  t: T
): ReportStat[] {
  const loadBalancerIps = ingress.loadBalancerIps;
  return [
    {
      label: t("columns", "class"),
      value: controller?.resolved
        ? controller.resolved
        : ingress.className || t("empty", "clusterDefault"),
      role: controller && !controller.resolved ? "err" : undefined,
    },
    {
      label: t("columns", "hostnames"),
      value: String(ingress.rules.length),
    },
    { label: "TLS", value: String(ingress.tlsHosts.length) },
    {
      label: t("columns", "loadBalancer"),
      value:
        loadBalancerIps.length > 0
          ? loadBalancerIps.join(", ")
          : t("empty", "pendingInline"),
      role: loadBalancerIps.length > 0 ? undefined : "warn",
    },
  ];
}

export function ingressRulesSection(ingress: IngressInfo, t: T): PlacedSection {
  const rows = ingress.rules.flatMap((rule) =>
    rule.paths.map((path) => ({
      cells: [
        { text: rule.host || t("empty", "allHosts"), mono: true },
        { text: path.path, mono: true },
        { text: path.pathType },
        path.resourceBackend
          ? { text: path.resourceBackend, mono: true }
          : path.backendService
            ? {
                text: path.backendService,
                ref: refOf({
                  kind: ResourceType.Service,
                  name: path.backendService,
                  namespace: ingress.namespace,
                }),
              }
            : { text: t("empty", "noBackend"), role: "warn" as const },
        { text: path.backendPort || "–" },
      ],
    }))
  );
  return {
    id: "rules",
    order: ORDER.own,
    title: t("columns", "rules"),
    icon: iconSvg(Route),
    count: rows.length,
    body: {
      type: "table",
      columns: [
        t("columns", "host"),
        t("columns", "path"),
        t("columns", "pathType"),
        t("columns", "backend"),
        t("columns", "port"),
      ],
      rows,
      more: null,
    },
  };
}

export function ingressTlsSection(ingress: IngressInfo, t: T): PlacedSection {
  return {
    id: "tls",
    order: ORDER.own,
    title: "TLS",
    icon: iconSvg(Lock),
    count: ingress.tlsConfigs.length,
    body: {
      type: "table",
      columns: [t("columns", "hostnames"), t("columns", "secret")],
      rows: ingress.tlsConfigs.map((config) => ({
        cells: [
          {
            text: config.isCatchAll
              ? t("empty", "catchAllAppliesToRest")
              : config.hosts.join(", ") || t("empty", "noHosts"),
          },
          config.secretName
            ? {
                text: config.secretName,
                ref: refOf({
                  kind: ResourceType.Secret,
                  name: config.secretName,
                  namespace: ingress.namespace,
                }),
              }
            : { text: t("empty", "autoGenerated"), quiet: true },
        ],
      })),
      more: null,
    },
  };
}

/**
 * What the Ingress page adds to Share: its class, its hosts and TLS reach,
 * the rules that route to a backend and the TLS configs behind them. Traffic
 * and connections are the frame's own, Ingress is a connected kind.
 */
export function useIngressShare(
  ingress: IngressInfo | undefined,
  controller: IngressClassBinding | undefined
): () => ShareContribution {
  const t = useT();
  return useCallback((): ShareContribution => {
    if (!ingress) return {};
    return {
      stats: ingressStats(ingress, controller, t),
      sections: [
        ingressRulesSection(ingress, t),
        ingressTlsSection(ingress, t),
      ],
    };
  }, [ingress, controller, t]);
}
